# Generated by Django 5.1.6 on 2025-02-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_requests_when_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
