# Generated by Django 5.1.6 on 2025-02-16 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_business_businesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_requests', to='users.business'),
        ),
    ]
