# Generated by Django 5.1.6 on 2025-02-16 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_requests_business'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='history',
            name='users_histo_technic_870faa_idx',
        ),
        migrations.RemoveField(
            model_name='history',
            name='technician',
        ),
        migrations.AddField(
            model_name='history',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to='users.business'),
        ),
        migrations.AddField(
            model_name='history',
            name='request_type',
            field=models.CharField(choices=[('user', 'User'), ('business', 'Business')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='requests',
            name='request_type',
            field=models.CharField(choices=[('user', 'User'), ('business', 'Business')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='history',
            index=models.Index(fields=['business'], name='users_histo_busines_4b1c0d_idx'),
        ),
    ]
