# Generated by Django 5.1.6 on 2025-02-16 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_history_users_histo_technic_870faa_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='request_type',
        ),
    ]
